version: '3'

services:
  mysql_db:
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - ./dbdata:/var/lib/mysql/